title: "Daily Dev Tracker"
description: "A minimal and sleek daily developer productivity tracker."
author: "Devansh"

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
